database:
  user: "v1lezz"
  password: "1234"
  host: "db"
  port: 5432
  database: "comics"
index:
  index_file: "index.json"
app:
  source_url: "xkcd.com"
  parallel: 10
server:
  port: 9000
  concurrency_limit: 10
  rate_limit: 10
auth:
  token_max_time: 10m